# Generated by Django 6.0.3 on 2026-05-27 09:21

from django.db import migrations, models

def seed_coupons(apps, schema_editor):
    from django.utils import timezone
    import datetime
    Coupon = apps.get_model('orders', 'Coupon')
    
    now = timezone.now()
    valid_from = now - datetime.timedelta(days=1)
    valid_to = now + datetime.timedelta(days=365) # Valid for 1 year
    
    # 1. SOLEVAULT20
    Coupon.objects.get_or_create(
        code='SOLEVAULT20',
        discount_type='percentage',
        discount_value=20.00,
        min_spend=1000.00,
        max_discount=1500.00,
        active=True,
        valid_from=valid_from,
        valid_to=valid_to
    )
    
    # 2. WELCOME500
    Coupon.objects.get_or_create(
        code='WELCOME500',
        discount_type='fixed',
        discount_value=500.00,
        min_spend=2000.00,
        active=True,
        valid_from=valid_from,
        valid_to=valid_to
    )

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
            ],
        ),
        migrations.RunPython(seed_coupons),
    ]
