# Generated by Django 6.0.3 on 2026-06-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_status',
            field=models.CharField(choices=[('none', 'None'), ('requested', 'Return Requested'), ('approved', 'Returned/Approved'), ('rejected', 'Return Rejected')], default='none', max_length=20),
        ),
    ]
