# Generated by Django 6.0.3 on 2026-04-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_created_at_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('leather', 'Leather'), ('suede', 'Suede'), ('mesh', 'Mesh'), ('canvas', 'Canvas')], default='mesh', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(choices=[('casual', 'Casual'), ('sports', 'Sports'), ('formal', 'Formal')], default='casual', max_length=20),
        ),
    ]
