# Generated by Django 6.0.3 on 2026-06-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_categoryoffer_productoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gender',
        ),
    ]
